[phases.setup]
nixPkgs = ["php80", "python38", "php80Extensions.mysqli", "php80Extensions.mbstring"]

[phases.build]
cmds = ["echo 'Building ChronoGen...'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t saoo"
